server {
    listen 80;
    listen [::]:80;
    server_name 95.158.64.196;

    location = /email-flow {
        return 301 /email-flow/;
    }

    location /email-flow/ {
        proxy_pass http://127.0.0.1:8085/email-flow/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
